### ISSUE TITLE
Panel Corner Output[BUG]

### ISSUE THREAD

**Issue by colin99d** [Textualize/rich#1830]
Hello! Thanks for putting together such a great library. I am not sure whether this is a feature or a bug but the `Panel` feature provides different outputs on windows and max/linux for the corners. On mac/linux we see `\u256d` (&#9581;) being used, while windows uses `\u250c` (&#9484;). This has little impact on the UX, however; it makes testing for changes in output and stored output complicated. We tried adjusting our console with safe_box=True and legacy_windows=True, however; this does not resolve the issue.

**Comment by aroberge** [comment]
@colin99d I'm just a regular user, and not associated with Rich, but are you using the new Windows terminal?  I see a rounded corner when using the new Windows Terminal app, and a square corner when using the old Command Prompt "app".

**Comment by colin99d** [comment]
Thanks for the quick response! The issue is this for our automated tests we do not use windows terminal. Here is our YAML for the environment: https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/.github/workflows/windows.yml.

**Comment by willmcgugan** [comment]
I usually advise folk *not* to explicitly test output due to issues like these. Rich will adapt the output so that it renders appropriately on the given platform. Additionally, I don't guarantee that the output will be byte for byte identical across minor versions, only that the output will look correct to the user.

Generally it is better to check the things being printed. For instance, test that the Panel has the expect attributes prior to printing.

The issue you are seeing with panels is because those round corners don't always render properly on legacy windows, it depends on the user's font choice and Rich has no way of knowing what the terminal can render.

If it can't be avoided, there are a few arguments you should consider setting on the Console:

```python
color_system="truecolor"  # Or pick another console system
legacy_windows=False  # Probably the source of your panel issue, the corners are replaces only on legacy windows 
_environ={}  # Blank set of environment variables. 
```

If you want to be more explicit about testing the output on Windows, I'm afraid your tests will have to take in to account platform differences.

**Comment by colin99d** [comment]
Thanks for the insight!
