### ISSUE TITLE
[BUG] time remaining estimate doesn't work on slow tasks

### ISSUE THREAD

**Issue by rvalieris** [Textualize/rich#2282]
**Describe the bug**

the `TimeRemainingColumn()` never shows an estimate if the task is slower than speed_estimate_period (default 30 seconds)

code to reproduce:
```python
import time
import rich.progress

p = rich.progress.Progress(
	*rich.progress.Progress.get_default_columns(),
	rich.progress.TimeElapsedColumn()
)

task = p.add_task(description='test')

with p:
	for i in p.track(range(20), task_id=task):
		time.sleep(60)
```

this happens because of this code:
https://github.com/Textualize/rich/blob/1772458f80924c78fa3a8d0260bca9762ad86e18/rich/progress.py#L1441-L1446

the progresssamples older than `speed_estimate_period` are removed from the queue before a speed estimate can be calculated.

I'm using rich-12.4.1 on linux.

**Comment by willmcgugan** [comment]
You can increase `speed_estimate_period` via the Progress constructor.

**Comment by rvalieris** [comment]
yes I understand I can change the period, but in reality I don't know how long the task will run for, so what number should I increase to ?

I was hopping the time remaining estimate would work for any task, whether it takes 10 seconds or 2 hours to finish.

**Comment by 0phoff** [comment]
Sorry for reopening a closed issue, but would it be an option to allow `speed_estimate_period` to be set to **None** or **-1** to disable this filter ?
I quickly looked through the code and it seems [pretty trivial](https://github.com/Textualize/rich/blob/master/rich/progress.py#L1449-L1453) to add.
I am willing to implement it and send a PR, but wanted to know if @willmcgugan likes the idea or not.

The reason for adding this is that we sometimes have very consistent processes (eg. a Deep Learning training epoch) that still take hours to complete. In these scenarios it is nice to have an estimate finishing time, even if it is not super accurate (most DL users know to take these estimates with a grain of salt, but it is still nice to have them!).
As the time per epoch varies drastically depending on dataset size, model choice, and compute platform, it is virtually impossible to find a good value for `speed_estimate_period`. I could set it to a ridicule number, but IMO it is nicer if the API allows you to set it to **None** to disable it.

The default value would still be unchanged (30sec), but this allows "more advanced" users to get around it.
Since multiple columns depend on this Speed computation, it is easier to add it as an option to Rich, rather than having a user reimplement (TimeRemainingColumn, SpeedColumn, etc) to work around it.

**Comment by gaardhus** [comment]
I think @0phoff's suggestion is great! Any thoughts on it @willmcgugan? 

Also, should the optionals in the [docstring](https://github.com/Textualize/rich/blob/master/rich/progress.py#L1050-L1064) not be updated? 

```
    Args:
        console (Console, optional): Optional Console instance. Default will an internal Console instance writing to stdout.
        auto_refresh (bool, optional): Enable auto refresh. If disabled, you will need to call `refresh()`.
        refresh_per_second (Optional[float], optional): Number of times per second to refresh the progress information or None to use default (10). Defaults to None.
        speed_estimate_period: (float, optional): Period (in seconds) used to calculate the speed estimate. Defaults to 30.
        transient: (bool, optional): Clear the progress on exit. Defaults to False.
        redirect_stdout: (bool, optional): Enable redirection of stdout, so ``print`` may be used. Defaults to True.
        redirect_stderr: (bool, optional): Enable redirection of stderr. Defaults to True.
        get_time: (Callable, optional): A callable that gets the current time, or None to use Console.get_time. Defaults to None.
        disable (bool, optional): Disable progress display. Defaults to False
        expand (bool, optional): Expand tasks table to fit width. Defaults to False.
    """
    ```
