### ISSUE TITLE
duplicated plots in jupyter

### ISSUE THREAD

**Issue by joamatab** [Textualize/rich#2803]
How can we avoid having duplicated plots on jupyter?

When I run

```
import gdsfactory as gf
gf.components.bend_circular()
```

I get one plot in jupyter, thanks to  defining `def _repr_html_(self)`

However when I run 
```
from rich import pretty

pretty.install()
gf.components.bend_circular()
```

I get two plots of the same component.

**Comment by willmcgugan** [comment]
What version of Jupyter?

**Comment by joamatab** [comment]
I have seen it on 3.5.2  and also on  3.6.1

Also I can see it on the docs of the package where we modify the `_repr_html_(self)`
https://gdsfactory.github.io/gdsfactory/notebooks/03_cells_autoname_and_cache.html#

```
A high level console interface.                                            │
│                                                                            │
│ ╭────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=115 ColorSystem.TRUECOLOR>                              │ │
│ ╰────────────────────────────────────────────────────────────────────────╯ │
│                                                                            │
│     color_system = 'truecolor'                                             │
│         encoding = 'utf-8'                                                 │
│             file = <ipykernel.iostream.OutStream object at 0x7efcfe5e6050> │
│           height = 100                                                     │
│    is_alt_screen = False                                                   │
│ is_dumb_terminal = False                                                   │
│   is_interactive = False                                                   │
│       is_jupyter = True                                                    │
│      is_terminal = False                                                   │
│   legacy_windows = False                                                   │
│         no_color = False                                                   │
│          options = ConsoleOptions(                                         │
│                        size=ConsoleDimensions(width=115, height=100),      │
│                        legacy_windows=False,                               │
│                        min_width=1,                                        │
│                        max_width=115,                                      │
│                        is_terminal=False,                                  │
│                        encoding='utf-8',                                   │
│                        max_height=100,                                     │
│                        justify=None,                                       │
│                        overflow=None,                                      │
│                        no_wrap=False,                                      │
│                        highlight=None,                                     │
│                        markup=None,                                        │
│                        height=None                                         │
│                    )                                                       │
│            quiet = False                                                   │
│           record = False                                                   │
│         safe_box = True                                                    │
│             size = ConsoleDimensions(width=115, height=100)                │
│        soft_wrap = False                                                   │
│           stderr = False                                                   │
│            style = None                                                    │
│         tab_size = 8                                                       │
│            width = 115                                                     │
╰────────────────────────────────────────────────────────────────────────────╯
╭─── <class 'rich._windows.WindowsConsoleFeatures'> ────╮
│ Windows features available.                           │
│                                                       │
│ ╭───────────────────────────────────────────────────╮ │
│ │ WindowsConsoleFeatures(vt=False, truecolor=False) │ │
│ ╰───────────────────────────────────────────────────╯ │
│                                                       │
│ truecolor = False                                     │
│        vt = False                                     │
╰───────────────────────────────────────────────────────╯
╭────── Environment Variables ───────╮
│ {                                  │
│     'TERM': 'xterm-color',         │
│     'COLORTERM': 'truecolor',      │
│     'CLICOLOR': '1',               │
│     'NO_COLOR': None,              │
│     'TERM_PROGRAM': 'tmux',        │
│     'COLUMNS': None,               │
│     'LINES': None,                 │
│     'JUPYTER_COLUMNS': None,       │
│     'JUPYTER_LINES': None,         │
│     'JPY_PARENT_PID': '715767',    │
│     'VSCODE_VERBOSE_LOGGING': None │
│ }                                  │
╰────────────────────────────────────╯
platform="Linux"
```

**Comment by willmcgugan** [comment]
Jupyter lab, Jupyter notebook, VScode ?

**Comment by joamatab** [comment]
jupyter-lab

**Comment by agoose77** [comment]
I think this is a bug in the `gdsfactory` library; they use side-effects in `_repr_html_` rather than returning HTML. As such, rich probably invokes multiple display methods.

**Comment by blois** [comment]
Specifically https://github.com/gdsfactory/gdsfactory/blob/b1d857446e1918b6f3db5b1cce3ba4de165652a5/gdsfactory/component.py#L1253 which leads to https://github.com/gdsfactory/gdsfactory/blob/b1d857446e1918b6f3db5b1cce3ba4de165652a5/gdsfactory/component.py#L1271.

If multiple reprs are needed then `__repr_mimebundle__` may be a better approach?

**Comment by minrk** [comment]
If they want to keep the side-effect pattern, [`_ipython_display_()`](https://ipython.readthedocs.io/en/stable/config/integrating.html#MyObject._ipython_display_) is the method for that. That would be the shortest path to a solution, I think.

As @blois mentioned, the direct cause is the side effects in `_repr_html_`. But since the `_ipy_display_hook` _calls_ all possible IPython hooks, IPython's own display formatter also calls the same hook, triggering the side effect a second time.

If `_repr_html_` were fixed to follow the spec and _return_ the html representation (note: plotting matplotlib figures does _not_ usually produce HTML, it produces a png or jpeg output), the duplication would be solved, but the whole plot would still be rendered twice. One would just be discarded.

I think rich's IPython hook as implemented now doesn't _quite_ fit the design of IPython's display formatters as it's implemented today. There are two classes:

1. the [DisplayFormatter](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.formatters.html#IPython.core.formatters.DisplayFormatter), which is the object responsible for selecting and dispatching renderers for individual formatters (available as `get_ipython().display_formatter`), and
2. the individual subclasses of [BaseFormatter](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.formatters.html#IPython.core.formatters.BaseFormatter), which are registered by mime-type as `ip.display_formatter.formatters` and should _return_ representations without side effects.

Currently, `_ipy_display_hook` registers itself as `text/plain` but actually relies on side effects to display text. I'm assuming this is why other formats are  considered - if rich and the HTMLFormatter both produce output, you'll see it twice. But this isn't how plain text reprs are expected to behave. Rich is reimplementing logic in DisplayFormatter and the frontend (output format _selection_) at the level of a single formatter (text/plain), which (in IPython's opinion) should not concern itself with what other formats are computed.

IPython and Jupyter generally expect _multiple_ representations of outputs, and `text/plain` is ~always present as a fallback. I think the right fix is for rich's `_ipy_display_hook` to remove its checks for whether it should run (which don't work in general because formatter functions can also be registered without special method names using `formatter.for_type`) and compute and _return_ its text representation unconditionally, [as is done in IPython's default pretty printer](https://github.com/ipython/ipython/blob/9663a9adc4c87490f1dc59c8b6f32cdfd0c5094a/IPython/core/formatters.py#L694-L708). It's up to the DisplayFormatter to pick which representations to _compute_, and up to the frontend to pick which representation to display, and multiple frontends or nbconvert exports may pick different formats to support or prefer.
